version: "3"

services:

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:15.5-bookworm
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # mails in local environ
  mailhog:
    image: mailhog/mailhog:latest
    logging:
        driver: 'none' # disable saving logs
    ports:
      - 1025:1025 # SMTP server port
      - 8025:8025 # Web UI
    user: root
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /mailhog-email-folder
    volumes:
      - mailhog_kutt_data:/mailhog-email-folder

volumes:
  redis_data:
  postgres_data:
  mailhog_kutt_data:
