apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
    namespace: url-shortener
    name: github-token-secret
spec:
    type: kv-v2
    mount: k8s/kv/kave-tech-services
    path: github_token

    destination:
        name: github-token-secret
        create: true
        type: "kubernetes.io/dockerconfigjson"

    refreshAfter: 10m