apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
    namespace: {{ .Values.kutt.namespace }}
    name: url-shortener-secrets
spec:
    type: kv-v2
    mount: k8s/kv/kave-tech-services
    path: url-shortener

    destination:
        name: url-shortener-secrets
        create: true

    refreshAfter: 10m